config/routes.rb
Hotornot::Application.routes.draw do

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure" #redirect('/', status: 302)
  match "/signout", to: "sessions#destroy", as: :signout
  resources :funnies do
    member do
      get :upvote
      get :downvote
    end
  end

  root to: "funnies#index"

end

app/models/casted_vote.rb
class CastedVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :funny
  attr_accessible :funny, :value, as: :admin
end

app/models/funny.rb
class Funny < ActiveRecord::Base
  attr_accessible :title, :pic
  belongs_to :user
  has_many :casted_votes
  has_many :voting_users, through: :casted_votes, source: :user

  has_attached_file :pic,
                    :styles => {
                                :thumbnail => "90x",
                                :medium => "300x",
                                :large => "500x"
                               },
                    :default_url => "/images/:style/missing.png"
  validates :title, length: { minimum: 2 }
  validates :title, presence: true

  def upvoted!
    self.upvotes = self.upvotes.succ
    self.netvotes = self.netvotes.succ
    save!
  end

  def downvoted!
    self.downvotes = self.downvotes.pred
    self.netvotes = self.netvotes.pred
    save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid
  has_many :funnies
  has_many :casted_votes
  has_many :voted_funnies, through: :casted_votes, source: :funny

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

  def owns?(funny)
    funny.user_id == self.id
  end

  def voted?(funny)
    voted_funnies.find_by_id(funny)
  end

  def visitor?
    false
  end

  def upvote(funny)
    return if voted?(funny)
    casted_votes.create!({funny: funny, value: 1}, as: :admin )
    funny.upvoted!
  end

  def downvote(funny)
    return if voted?(funny)
    casted_votes.create!({funny: funny, value: -1}, as: :admin )
    funny.downvoted!
  end
end

app/models/visitor.rb
class Visitor
  def visitor?
    true
  end

  def method_missing(method_name, *args, &block)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  protected
  def must_by_logged_in
    redirect_to root_path, notice: "You must be logged in to do this" if current_user.visitor?
  end

  private

  def current_user
    @current_user ||= if session[:user_id]
                        user = User.find_by_id(session[:user_id])
                        user ? user : Visitor.new # in case of corrupted session id
                      else
                        Visitor.new
                      end
  end
end

app/controllers/funnies_controller.rb
class FunniesController < ApplicationController
  before_filter :must_by_logged_in, except: [:index, :show]
  # GET /funnies
  # GET /funnies.json
  def index
    @funnies = Funny.order("created_at desc").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @funnies }
    end
  end

  def upvote
    if (@funny = Funny.find(params[:id]))
      current_user.upvote(@funny)
      redirect_to @funny
    else
      redirect_to @funny, notice: "Couldn't find your funny pic"
    end
  end

  def downvote
    if (@funny = Funny.find(params[:id]))
      current_user.downvote(@funny)
      redirect_to @funny
    else
      redirect_to @funny, notice: "Couldn't find your funny pic"
    end
  end

  # GET /funnies/1
  # GET /funnies/1.json
  def show
    @funny = Funny.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @funny }
    end
  end

  # GET /funnies/new
  # GET /funnies/new.json
  def new
    @funny = current_user.funnies.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @funny }
    end
  end

  # GET /funnies/1/edit
  def edit
    @funny = current_user.funnies.find(params[:id])
  end

  # POST /funnies
  # POST /funnies.json
  def create
    @funny = current_user.funnies.new(params[:funny])
    respond_to do |format|
      if @funny.save
        format.html { redirect_to @funny, notice: 'Funny was successfully created.' }
        format.json { render json: @funny, status: :created, location: @funny }
      else
        format.html { render action: "new" }
        format.json { render json: @funny.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /funnies/1
  # PUT /funnies/1.json
  def update
    @funny = current_user.funnies.find(params[:id])

    respond_to do |format|
      if @funny.update_attributes(params[:funny])
        format.html { redirect_to @funny, notice: 'Funny was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @funny.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funnies/1
  # DELETE /funnies/1.json
  def destroy
    @funny = current_user.funnies.find(params[:id])
    @funny.destroy

    respond_to do |format|
      format.html { redirect_to funnies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def failure
    render json: params
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funnies_helper.rb
module FunniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/funnies/_form.html.haml
= form_for @funny,  html: { multipart: true } do |f|
  - if @funny.errors.any?
    #error_explanation
      %h2= "#{pluralize(@funny.errors.count, "error")} prohibited this funny from being saved:"
      %ul
        - @funny.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :pic
    = f.file_field :pic
  .actions
    = f.submit 'Save'

app/views/funnies/edit.html.haml
%h1 Editing funny

= render 'form'

= link_to 'Show', @funny
\|
= link_to 'Back', funnies_path

app/views/funnies/index.html.haml
%h1 Listing funnies
= link_to 'Upload a Funny', new_funny_path unless current_user.visitor?

%ul
  - @funnies.each do |funny|
    %li
      %div= funny.title
      %div= link_to image_tag(funny.pic.url(:medium)), funny
      %div Score: #{funny.netvotes}
      .actions
      - if current_user && funny.user == current_user
        = link_to 'Edit', edit_funny_path(funny)
        = link_to 'Destroy', funny, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/funnies/new.html.haml
%h1 New funny

= render 'form'

= link_to 'Back', funnies_path

app/views/funnies/show.html.haml
%p#notice= notice

%h1= @funny.title
%div= image_tag @funny.pic.url(:large)
%div Current Score #{@funny.netvotes}
- unless current_user.voted?(@funny)
  = link_to "+1", upvote_funny_path(@funny)
  = link_to "-1", downvote_funny_path(@funny)

= link_to 'Edit', edit_funny_path(@funny) if current_user.owns?(@funny)
\|
= link_to 'Back', funnies_path

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Funny or Not
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

%body
  - if current_user.visitor?
    = link_to "Sign in with Facebook", "/auth/facebook"
  - else
    Welcome #{current_user.name}!
    = link_to "Sign Out", signout_path

  .notice= flash[:notice]

  = yield